name: countapp_using_container_presentation
description: count-up app using Redux architecture with the idea separating Widget into container and presentation

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  redux: ^3.0.0
  flutter_redux: ^0.5.2
  http: ^0.12.0

dev_dependencies:
  test: ^1.6.0
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true